- name: Test SNMP Location
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Set SNMP location
      ios_config:
        lines:
          - snmp-server location VilniusTech_Serverine

    - name: Save running-config
      cisco.ios.ios_command:
        commands: write memory